export const CHAT_ACTIONS = Object.freeze([
  "add-personal-task",
  "add-work-task",
  "complete-personal-task",
  "complete-work-task",
  "reopen-personal-task",
  "reopen-work-task",
  "delete-personal-task",
  "delete-work-task",
  "update-personal-task",
  "update-work-task",
  "add-reminder",
  "complete-reminder",
  "update-reminder",
  "delete-agenda-item",
  "add-calendar-event",
  "update-calendar-event",
  "add-learning",
  "complete-learning",
  "add-project-note",
  "archive-project-note",
]);

export const ACTION_LABELS = Object.freeze({
  "add-personal-task": "Νέο Personal task",
  "add-work-task": "Νέο Work task",
  "complete-personal-task": "Ολοκλήρωση Personal task",
  "complete-work-task": "Ολοκλήρωση Work task",
  "reopen-personal-task": "Επαναφορά Personal task",
  "reopen-work-task": "Επαναφορά Work task",
  "delete-personal-task": "Διαγραφή Personal task",
  "delete-work-task": "Διαγραφή Work task",
  "update-personal-task": "Επεξεργασία Personal task",
  "update-work-task": "Επεξεργασία Work task",
  "add-reminder": "Νέα υπενθύμιση",
  "complete-reminder": "Ολοκλήρωση υπενθύμισης",
  "update-reminder": "Επεξεργασία υπενθύμισης",
  "delete-agenda-item": "Διαγραφή από Πρόγραμμα",
  "add-calendar-event": "Νέο Calendar event",
  "update-calendar-event": "Επεξεργασία Calendar event",
  "add-learning": "Νέο Learning item",
  "complete-learning": "Ολοκλήρωση Learning item",
  "add-project-note": "Νέα σημείωση έργου",
  "archive-project-note": "Αρχειοθέτηση σημείωσης έργου",
});
