#!/usr/bin/env bash

sudo mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts
sudo wget -O "Hack.zip" "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip"
sudo unzip Hack.zip && sudo rm Hack.zip
fc-cache -fv
