#!/usr/bin/env bash

case "$(uname -s)" in
    Darwin) brew install git ;;
    *) sudo apt install -y git ;;
esac

git config --global user.email "liakos.koulaxis@yahoo.com"
git config --global user.name "kx0101"
git config --global core.editor=nvim
