#!/usr/bin/env bash

version="v0.12.0"

echo "version: \"$version\""

if [ "$(uname -s)" = "Darwin" ]; then
    brew install neovim luarocks tree-sitter-cli
    luarocks install luasocket || true
    luarocks install luacheck || true
    exit 0
fi

if [ ! -d $HOME/neovim ]; then
    git clone https://github.com/neovim/neovim.git $HOME/neovim
fi

sudo apt -y install cmake gettext lua5.1 liblua5.1-0-dev

git -C ~/neovim fetch --all
git -C ~/neovim checkout $version

make -C ~/neovim clean
make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make -C ~/neovim install

wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
tar zxpf luarocks-3.11.1.tar.gz
cd luarocks-3.11.1
./configure && make && sudo make install
sudo luarocks install luasocket
luarocks install luacheck

# tree-sitter CLI: required by nvim-treesitter (main branch) to build parsers
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
cargo install tree-sitter-cli
