#!/usr/bin/env bash

mkdir -p ~/.omnisharp

cd ~/.omnisharp
curl -L https://github.com/OmniSharp/omnisharp-roslyn/releases/latest/download/omnisharp-linux-x64-net6.0.tar.gz -o omnisharp.tar.gz

tar -xzf omnisharp.tar.gz
rm omnisharp.tar.gz

cd ~/.omnisharp && touch omnisharp.json
echo '{
  "RoslynExtensionsOptions": {
    "enableAnalyzersSupport": true
  },
  "FormattingOptions": {
    "enableEditorConfigSupport": true
  }
}' > omnisharp.json
