#!/usr/bin/env bash

case "$(uname -s)" in
    Darwin)
        # macOS already ships zsh as the default login shell
        ;;
    *)
        sudo apt install -y zsh
        hash -r
        sudo chsh -s $(which zsh)
        ;;
esac

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
