- name: Add Amazon Corretto GPG key
  apt_key:
    url: https://apt.corretto.aws/corretto.key
    state: present

- name: Add Amazon Corretto repository
  apt_repository:
    repo: "deb https://apt.corretto.aws stable main"
    state: present

- name: Install Corretto JDK 22
  apt:
    name: java-22-amazon-corretto-jdk
    state: present
