- name: Install Git
  apt:
    name: git
    state: present

- name: Configure Git global user name
  command: git config --global user.name "{{ git_user }}"
  become: yes
  become_user: "{{ deploy_user }}"  

- name: Configure Git global user email
  command: git config --global user.email "{{ git_email }}"
  become: yes
  become_user: "{{ deploy_user }}"
