- name: Install Go
  command: "/opt/homebrew/bin/brew install go"

- name: Install Go tools
  shell: |
    go install golang.org/x/tools/cmd/godoc@latest
    go install golang.org/x/tools/cmd/guru@latest
