- name: Install dependencies for building Neovim
  apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - libtool
      - libtool-bin
      - pkg-config
      - libgtk-3-dev
      - libevdev-dev
      - libudev-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libfontconfig1-dev
      - libharfbuzz-dev
    state: present

- name: Download Neovim 0.10.2
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.10.2/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"

- name: Extract Neovim 0.10.2
  unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: Create a symlink for Neovim
  file:
    src: "/usr/local/nvim-linux64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link

- name: Install Packer (wbthomason/packer.nvim)
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "/home/{{ deploy_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master
    depth: 1

- name: Copy Neovim configuration from current directory
  copy:
    src: "../nvim"
    dest: "/home/{{ deploy_user }}/.config/"
    mode: '0755'
    remote_src: no

