- name: Remove Neovim installed via package manager
  become: yes
  apt:
    name: neovim
    state: absent
  ignore_errors: yes

- name: Remove existing Neovim installations (manual installations)
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/usr/local/bin/nvim"
    - "/usr/local/nvim-linux64"
    - "/home/{{ deploy_user }}/.config/nvim"
    - "/home/{{ deploy_user }}/.local/share/nvim"
    - "/tmp/nvim-linux64.tar.gz"

- name: Install dependencies for building Neovim
  become: yes
  apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - libtool
      - libtool-bin
      - pkg-config
      - libgtk-3-dev
      - libevdev-dev
      - libudev-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libfontconfig1-dev
      - libharfbuzz-dev
    state: present
    update_cache: yes

- name: Download Neovim 0.10.2
  become: yes
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.10.2/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"

- name: Extract Neovim 0.10.2
  become: yes
  unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: Create a symlink for Neovim
  become: yes
  file:
    src: "/usr/local/nvim-linux64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
    force: yes

- name: Verify Neovim version
  command: nvim --version
  register: neovim_version

- name: Display installed Neovim version
  debug:
    msg: "Installed Neovim version: {{ neovim_version.stdout_lines[0] }}"

- name: Install Packer (wbthomason/packer.nvim)
  become: no
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "/home/{{ deploy_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master
    depth: 1
  become_user: "{{ deploy_user }}"

- name: Copy Neovim configuration from current directory
  become: no
  copy:
    src: "../nvim"
    dest: "/home/{{ deploy_user }}/.config/"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0755'
    remote_src: no
