- name: Clone Neovim repo
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: /tmp/neovim
    version: v0.10.0

- name: Build Neovim
  shell: |
    make CMAKE_BUILD_TYPE=Release
    sudo make install
  args:
    chdir: /tmp/neovim

- name: Install Packer (wbthomason/packer.nvim)
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: main

- name: Copy Neovim configuration from current directory
  copy:
    src: "nvim"
    dest: "~/.config"
    remote_src: yes
