- name: Add Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: Install Neovim
  apt:
    name: neovim
    state: present

- name: Install Packer (wbthomason/packer.nvim)
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "/home/{{ deploy_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master
    depth: 1

- name: Copy Neovim configuration from current directory
  copy:
    src: "../nvim"
    dest: "/home/{{ deploy_user }}/.config/"
    mode: '0755'
    remote_src: no
