- name: Create fonts directory if it doesn't exist
  file:
    path: "/home/{{ deploy_user }}/.local/share/fonts"
    state: directory
    mode: '0755'

- name: Create Hack font directory
  file:
    path: "/home/{{ deploy_user }}/.local/share/fonts/Hack"
    state: directory
    mode: '0755'

- name: Download Hack Nerd Font
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip"
    dest: "/tmp/Hack.zip"
    mode: '0644'

- name: Unzip Hack Nerd Font
  unarchive:
    src: "/tmp/Hack.zip"
    dest: "/home/{{ deploy_user }}/.local/share/fonts/Hack"
    remote_src: yes

- name: Refresh font cache
  command: fc-cache -fv

- name: Verify Hack Nerd Font installation
  command: fc-list | grep "Hack"
  register: font_check
