- name: Install Node.js and NPM
  apt:
    name: npm
    state: present

- name: Install TypeScript and TS-Node globally
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - typescript
    - ts-node
