- name: Ensure Zsh is installed
  become: yes
  apt:
    name: zsh
    state: present

- name: Check if Oh My Zsh is already installed
  stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: oh_my_zsh_check

- name: Install Oh My Zsh if not already installed
  become: yes
  become_user: "{{ deploy_user }}"
  shell: |
    if [ ! -d "{{ ansible_env.HOME }}/.oh-my-zsh" ]; then
      curl -Lo /tmp/install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      chmod +x /tmp/install.sh
      /tmp/install.sh --skip-chsh --no-verify
    else
      echo "Oh My Zsh is already installed for {{ deploy_user }}"
    fi
  args:
    creates: "{{ user_home }}/.oh-my-zsh"

- name: Ensure .zshrc exists (copy template if missing)
  become: yes
  become_user: "{{ deploy_user }}"
  copy:
    src: "{{ user_home }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ user_home }}/.zshrc"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0644'
    remote_src: yes

- name: Configure Zsh theme to robbyrussell
  become: yes
  become_user: "{{ deploy_user }}"
  lineinfile:
    path: "{{ user_home }}/.zshrc"
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="robbyrussell"'
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0644'

- name: Add custom aliases and environment variables to .zshrc
  become: yes
  become_user: "{{ deploy_user }}"
  blockinfile:
    path: "{{ user_home }}/.zshrc"
    marker: "# BEGIN CUSTOM ZSH CONFIG"
    block: |
      # Custom Aliases
      alias vim='nvim'
      alias tmux-sessionizer="~/.dotfiles/scripts/tmux-sessionizer.sh"
      alias luamake='~/lua-language-server/3rd/luamake/luamake'

      # Environment Variables
      export PATH="/usr/local/bin/node:$PATH"
      export GOROOT="/usr/local/go"
      export GOPATH="$HOME/go"
      export PATH="$PATH:$GOROOT/bin:$GOPATH/bin:/usr/local/go/bin"
    state: present

- name: Change default shell to Zsh for the user
  become: yes
  user:
    name: "{{ deploy_user }}"
    shell: /usr/bin/zsh

- name: Verify Zsh configuration (simulate user shell)
  become: yes
  become_user: "{{ deploy_user }}"
  shell: "zsh -lc 'echo $PATH'"
  register: zsh_path_output

- name: Display Zsh PATH for verification
  debug:
    msg: "Current Zsh PATH for {{ deploy_user }}: {{ zsh_path_output.stdout }}"
