- name: Install Tmux
  apt:
    name: tmux
    state: present

- name: Copy tmux configuration from current directory
  copy:
    src: "{{ playbook_dir }}/../.tmux.conf"  
    dest: "/home/{{ deploy_user }}/.tmux.conf"
    remote_src: no

- name: Install Tmux Themepack (jimeh/tmux-themepack)
  git:
    repo: 'https://github.com/jimeh/tmux-themepack.git'
    dest: "/home/{{ deploy_user }}/.tmux-themepack"
    version: master
