- hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install zsh shell
    shell: name=zsh
    tags: 
    - zsh
  - name: Change shell
    shell: chsh -s `which zsh`
    tags: 
    - zsh
  - name: Install ohmyzsh
    shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
    when: "'/Users/elijahkoulaxis/.oh-my-zsh' is file"
    tags: 
    - zsh
  - name: Install zsh plugin auto-suggestions
    shell: 'git config --global --add safe.directory /Users/elijahkoulaxis/.oh-my-zsh/plugins/zsh-autosuggestions'
    tags: 
    - zsh
  - name: update our zshrc
    shell: sed -i '' "s/(git/(git zsh-autosuggestions/" ~/.zshrc
    tags: 
    - zsh
  - name: install nodejs
    shell: name=nodejs 
    tags:
    - node
  - name: install npm
    shell: name=npm
    tags:
    - node
  - name: Install n
    shell: npm install n 
    tags:
    - node
  - name: typescript 
    shell: npm install typescript 
    tags:
    - node
