- hosts: localhost
  become: yes

  vars_files:
  - vars/vars.yml    
  - vars/secure_vars.yml 

  pre_tasks:
    - name: Get the username running the deploy
      command: whoami
      register: username
      become: false

    - name: Set global username variable
      set_fact:
        deploy_user: "{{ username.stdout }}"

  tasks:
    - name: Update apt and upgrade system
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Git
      include_tasks: tasks/git.yml

    - name: Install oh-my-zsh
      include_tasks: tasks/ohmyzsh.yml

    - name: Install Neovim
      include_tasks: tasks/neovim.yml

    - name: Install Rust
      include_tasks: tasks/rust.yml

    - name: Install Corretto JDK 22
      include_tasks: tasks/corretto_jdk.yml

    - name: Install NPM, TypeScript, and tsnode
      include_tasks: tasks/npm.yml

    - name: Install Zsh and set it as default shell
      include_tasks: tasks/zsh.yml

    - name: Install Tmux
      include_tasks: tasks/tmux.yml

    - name: Install Docker
      include_tasks: tasks/docker.yml

    - name: Install Go and Go tools
      include_tasks: tasks/go.yml

    - name: Install FZF
      include_tasks: tasks/fzf.yml

    - name: Install Ripgrep
      include_tasks: tasks/ripgrep.yml

    - name: Install Hack Nerd Font
      include_tasks: tasks/nerd-font.yml
