- hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Install Git
      include_tasks: tasks/git.yml

    # - name: Install Neovim
    #   include_tasks: tasks/neovim.yml

    - name: Install Corretto JDK 22
      include_tasks: tasks/corretto_jdk.yml

    - name: Install NPM, TypeScript, and TS-Node
      include_tasks: tasks/npm.yml

    - name: Install PNPM
      include_tasks: tasks/pnpm.yml

    - name: Install Zsh and set it as default shell
      include_tasks: tasks/zsh.yml

    - name: Install Tmux
      include_tasks: tasks/tmux.yml

    - name: Install Docker
      include_tasks: tasks/docker.yml

    - name: Install Go and Go tools
      include_tasks: tasks/go.yml

    - name: Install FZF
      include_tasks: tasks/fzf.yml

    - name: Install Ripgrep
      include_tasks: tasks/ripgrep.yml

    - name: Install Xclip
      include_tasks: tasks/xclip.yml
